services:
  analyst-db:
    container_name: analyst-db
    image: postgres:15-alpine
    restart: always
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  analyst-rabbitmq:
    container_name: analyst-rabbitmq
    hostname: 'rabbitmq'
    image: rabbitmq:3.13.2
    restart: on-failure
    ports:
      - "5672:5672"
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  # chatgpt-proxy:
  #   container_name: chatgpt
  #   image: pawanosman/chatgpt:latest
  #   restart: on-failure
  #   ports:
  #     - 3040:3040
  #   env_file:
  #     - .env

volumes:
  postgres_data:
  rabbitmq_data:
